### ISSUE TITLE
All nav pages without permalinks will be considered "active" if current page also doesn't have a permalink 

### ISSUE THREAD

**Issue by deargle** [benbalter/retlab#42]
This line has the logic: https://github.com/benbalter/retlab/blob/25a911ef54b52a962d0d6a4d790904739204a7db/_includes/nav.html#L12

Fix: either give all nav pages a permalink, or change it to something like:

```html 
<li class="nav-item{% if nav_page.permalink and page.permalink == nav_page.permalink %} active{% endif %}">
```

**Comment by benbalter** [comment]
Thanks @deargle if you're willing to submit a pull request, I'd be happy to review it to get the change included.

**Comment by deargle** [comment]
Can do, but scratching my head because the .active style seems to have gone missing (not highlighting on ben.balter.com, anyway). Where would you prefer for that to be added back in? Pulling from chrome inspector, the now-missing style used to be this:

```css
.navbar-light .navbar-nav .show>.nav-link, .navbar-light .navbar-nav .active>.nav-link, .navbar-light .navbar-nav .nav-link.show, .navbar-light .navbar-nav .nav-link.active {
    color: rgba(0,0,0,0.9);
}
```
